Numpyは、Pythonで数値計算を行うためのライブラリで、特に行列や多次元配列の操作が得意です。
https://qiita.com/k-keita/items/4228839d2fdc8fde7e9e


In [15]:
import numpy as np

# 1次元配列を作成
arr_1d = np.array([1, 2, 3, 4, 5])
# 同じ種類のデータをまとめて管理できる
print("1次元配列:", arr_1d)
# 配列とは、たくさんのデータをまとめて、効率よく計算できるようにしたデータ構造。

1次元配列: [1 2 3 4 5]


In [4]:
arr = np.array([1, 2, 3])
arr + 1


array([2, 3, 4])

In [ ]:
# 2次元配列（行列）を作成
# 2次元配列（にじげんはいれつ）とは、縦と横の2つの方向をもつデータの並び” のことで
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2次元配列（行列）:")
print(arr_2d)


2次元配列（行列）:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# 配列の形状と次元を確認
print("配列の形状:", arr_2d.shape)  # (行数, 列数)
print("配列の次元:", arr_2d.ndim)   # 次元数


配列の形状: (3, 3)
配列の次元: 2


In [8]:
# 配列の特定の要素にアクセス
# 配列は 0 から始まる
print("要素 (0, 1):", arr_2d[1, 2])  # 0行1列目の要素（2）


要素 (0, 1): 6


In [9]:
arr_2d_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# 行列の加算
result_add = arr_2d + arr_2d_2
print("行列の加算:")
print(result_add)

# 行列の減算
result_sub = arr_2d - arr_2d_2
print("行列の減算:")
print(result_sub)


行列の加算:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
行列の減算:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [10]:
# 行列にスカラーを掛ける
result_scalar = arr_2d * 2
print("行列のスカラー倍:")
print(result_scalar)


行列のスカラー倍:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
# 行列の転置
result_transpose = arr_2d.T
print("行列の転置:")
print(result_transpose)


行列の転置:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
# 行列積（ドット積）
result_dot = np.dot(arr_2d, arr_2d_2.T)  # arr_2dとarr_2d_2の転置行列のドット積
print("行列積:")
print(result_dot)


行列積:
[[ 46  28  10]
 [118  73  28]
 [190 118  46]]


In [13]:
# 3x3のランダムな整数行列を生成（0から10未満の整数）
random_int = np.random.randint(0, 10, size=(3, 3))
print("ランダム整数行列:")
print(random_int)

# 3x3のランダムな浮動小数点数行列を生成（0から1未満）
random_float = np.random.rand(3, 3)
print("ランダム浮動小数点数行列:")
print(random_float)


ランダム整数行列:
[[1 2 1]
 [4 7 2]
 [6 9 0]]
ランダム浮動小数点数行列:
[[0.95220241 0.99279704 0.0431207 ]
 [0.50505922 0.42222534 0.42021329]
 [0.77871917 0.62834713 0.09892069]]


In [14]:
# 配列の平均、標準偏差、合計
print("平均値:", np.mean(arr_2d))
print("標準偏差:", np.std(arr_2d))
print("合計値:", np.sum(arr_2d))


平均値: 5.0
標準偏差: 2.581988897471611
合計値: 45
